config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :destroy], param: :username do
    get 'activate', on: :collection
  end
  get '/users', to: 'users#new'
  
  resource :session, only: [:new, :create, :destroy]
  get '/session', to: 'sessions#new'

  resources :subs, except: [:destroy], param: :title do
    member { post :subscribe }
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member { post :upvote }
    member { post :downvote }
  end
  get '/posts', to: 'subs#index'

  resources :comments, only: [:create, :show, :destroy] do
    member { post :upvote }
    member { post :downvote }
  end

  resources :pages, only: [:index]

  resources :searches, only: [:index]
  get '/search', to: 'searches#index'

  root 'pages#index'
end

app/models/user.rb
# email,            string,     unique, present
# username,         string,     unique, present
# password_digest,  string,             present
# session_token,    string,     unique, present
# activated,        boolean,            present
# activation_token, string,             present

class User < ApplicationRecord
  include Calcs

  attr_reader :password

  validates :email, :username, :password_digest, :session_token, :activation_token, presence: true
  validates :email, :username, :session_token, :activation_token, uniqueness: true
  validates :password, length: { minimum: MIN_PWORD, allow_nil: true }
  validates :username, length: { minimum: MIN_UNAME, maximum: MAX_UNAME }, format: { with: URL_SAFE_REGEX, 
      message: 'allows only letters, numbers, and symbols -_$.+!*()' }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  after_initialize :ensure_session_token, :ensure_activation_token

  before_destroy :reassign_entries

  has_many :subs,
    class_name: 'Sub',
    primary_key: :id,
    foreign_key: :moderator

  has_many :posts,
    class_name: 'Post',
    primary_key: :id,
    foreign_key: :author_id

  has_many :comments,
    class_name: 'Comment',
    primary_key: :id,
    foreign_key: :author_id

  has_many :subscriptions

  has_many :subscribed_subs,
    through: :subscriptions,
    source: :sub

  def score
    p_score = self.posts.includes(:votes).sum(:value)
    c_score = self.comments.includes(:votes).sum(:value)
    p_score + c_score
  end

  def reassign_entries
    account_id = User.find_by_username(DESTROYED).id

    User.transaction do
      self.subs.each do |sub|
        sub.moderator = account_id
        sub.save!
      end

      self.posts.each do |post|
        post.author_id = account_id
        post.save!
      end

      self.comments.each do |comment|
        comment.author_id = account_id
        comment.save!
      end
    end
  end

  def to_param
    self.username
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_activation_token
    self.activation_token ||= self.class.generate_activation_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def activate_user
    self.activated = true
    self.save!
  end

  def self.generate_session_token
    generate_token(:find_by_session_token)
  end

  def self.generate_activation_token
    generate_token(:find_by_activation_token)
  end

  def self.generate_token(find_by_method)
    token = SecureRandom::urlsafe_base64(16)

    token = SecureRandom::urlsafe_base64(16) while User.send(find_by_method, token)
    token
  end

  def self.find_by_credentials(email, pw)
    user = User.find_by_email(email)
    user && user.is_password?(pw) ? user : nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in, only: [:new, :create, :activate]
  before_action :wrong_user, only: [:destroy]
  before_action :deleted_user, only: [:show]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @url = activate_users_url(activation_token: @user.activation_token)
      render :activate
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_username(params[:username])
    @subs = @user.subs.alpha_order(:title).select(:title)
    @posts = @user.posts.create_order.includes(:votes, :subs)
    @comments = @user.comments.create_order.includes(:votes, :post)
    render :show
  end

  def destroy
    user = User.find_by_username(params[:username])

    if user.destroy
      flash[:notice] = 'Your account was deleted'
      redirect_to new_user_url
    else
      flash[:error] = 'Oops, something went wrong and you still exist'
      redirect_to user_url(user)
    end
  end

  def activate
    user = User.find_by_activation_token(params[:activation_token])

    if user
      handle_activation(user)
      redirect_to new_session_url
    else
      flash[:error] = 'User not found. Please register first'
      redirect_to new_user_url
    end
  end

  private

  def deleted_user
    return unless params[:username] == DESTROYED
    link = request.referrer || root_url
    redirect_to link
  end

  def wrong_user
    user = User.find_by_username(params[:username])
    return if current_user == user
    redirect_to user_url(user)
  end

  def handle_activation(user)
    if user.activated
      flash[:notice] = 'This account is already active'
    else
      flash[:notice] = 'You have successfully activated your account'
      user.activate_user
    end
  end

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def mixed_ordered_posts_comments(posts, comments)
    p_hash = post_hash(posts)
    c = comments.to_a

    c.each_with_index do |comment, idx|
      next unless p_hash.key?(comment.post_id)
      p_hash[comment.post_id] << comment
      c[idx] = nil
    end
    
    sort_posts_comments(p_hash, c)
  end  

  def post_hash(posts)
    h = {}
    posts.each { |post| h[post.id] = [post] }
    h
  end

  def sort_posts_comments(post_hash, comments_arr)
    post_hash.to_a.concat(comments_arr.reject(&:nil?)).sort_by do |el|
      el.is_a?(Array) ? el[1][0].created_at : el.created_at
    end
  end

  def separate_posts_comments(arr)
    [arr[1][0], arr[1][1..-1]]
  end

  def mix_posts_comments(posts, comments)
    posts.to_a.concat(comments.to_a).sort_by { |el| el.created_at }
  end
end

app/views/users/_confirm_delete.html.erb
<div class="modal hide" id="delete-account">
    <h2>Delete Your Account</h2>
    <p>Are you sure you want to delete your account?</p>
    <div class="modal-buttons">
        <%= button_to "Yes, Delete Me!", user_url(user), method: :delete, class: "delete-btn" %>
        <button id="keep_account" class="delete-btn stay">No, I'll Stay</button>
    </div>
</div>

app/views/users/_list.html.erb
<% users.each do |user| %>
    <%= link_to "users/#{user.username}", user_url(user) %>
<% end %>

app/views/users/activate.html.erb
<% @title = 'Fake Email' %>

<div class="form login email bottom-padding">

  <div class="art"></div>

  <div class="form-container">
    <div class="logo-img">
      <i class="fas fa-bread-slice"></i>
    </div>

    <h1>Welcome to Breddit: a Reddit clone, <%= @user.username %>!</h1>

    <p>Before you can use this site, you must activate your account. <%= link_to "Activate Now!", @url %></p>

    <p>Thanks for joining. Have fun and be safe!</p>

    <p>- The Breddit Team</p>

    <div class="notice">
      <p>
        It is a bad idea to activate accounts this way. Always send this link in a text or email.
        We are showing this message here due to Heroku deployment compatibility.
      </p>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% @title = "Register" %>
<div class="form login register bottom-padding">

  <div class="art"></div>

  <div class="form-container">

    <div class="logo-img">
      <i class="fas fa-bread-slice"></i>
    </div>

    <h1>Sign Up</h1>

    <%= link_to "Already own an account? Log in!", new_session_url %>

    <%= form_with model: @user, method: :post, local: true do |form| %>
      <div>
        <%= label :user, :email %>
        <%= form.text_field :email, value: @user.email, required: true, placeholder: "Email" %>
      </div>

      <div>
        <%= label :user, :username %>
        <%= form.text_field :username, value: @user.username, minlength: MIN_UNAME, maxlength: MAX_UNAME, required: true, placeholder: "Username" %>
      </div>

      <div>
        <%= label :user, :password %>
        <%= form.password_field :password, minlength: MIN_PWORD, required: true, placeholder: "Password" %>
      </div>

      <div>
        <%= form.submit "Register" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% @title = @user.username %>

<section class="user-details">
    <h2>users/<%= @user.username %></h2>
    <span class="details">Joined <%= @user.time_ago %> ago, score: <%= @user.score %> points</span>

    <% unless @subs.empty? %>
        <% sub_list = @subs.map { |sub| link_to sub.title, sub_url(sub) } %>
        <span class="details"><span class="heavy">Moderates:</span> <%= sub_list.join(' ').html_safe %></span>
    <% end %>

    <% if current_user == @user %>
        <button id="delete_user", class="delete-btn">Delete Account</button>

        <%= render "confirm_delete", user: @user %>
    <% end %>
</section>

<section class="page users bottom-padding">
<% mixed_ordered_posts_comments(@posts, @comments).each do |data| %>
    <% if data.is_a?(Array) %>
        <% post, comments = separate_posts_comments(data) %>
        <div>
            <div class="post-fragment">
                <%= render "posts/list", posts: [post], short: false %>
            </div>
            <div class="comments">
            <% comments.each do |comment| %>
                <div class="container indent flat">
                    <%= render "comments/single_comment", comment: comment %>
                </div>
            <% end %>
            </div>
        </div>
    <% else %>
        <div class="comments">
        <div class="container">
            <%= render "comments/single_comment", comment: data, quote: "→ #{link_to(data.post.title, post_url(data.post))}" %>
        </div>
        </div>
    <% end %>
<% end %>
</section>

<%= javascript_include_tag 'components/nested_comments' %>
<%= javascript_include_tag 'components/modal' %>