config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :destroy], param: :username do
    get 'activate', on: :collection
  end
  get '/users', to: 'users#new'
  
  resource :session, only: [:new, :create, :destroy]
  get '/session', to: 'sessions#new'

  resources :subs, except: [:destroy], param: :title do
    member { post :subscribe }
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member { post :upvote }
    member { post :downvote }
  end
  get '/posts', to: 'subs#index'

  resources :comments, only: [:create, :show, :destroy] do
    member { post :upvote }
    member { post :downvote }
  end

  resources :pages, only: [:index]

  resources :searches, only: [:index]
  get '/search', to: 'searches#index'

  root 'pages#index'
end

app/views/shared/_errors.html.erb
<% flash.each do |key, msg| %>
    <% if msg.is_a?(String) %>
        <div class="<%= key %>"><%= msg %></div>
    <% else %>
        <% msg.each do |string| %>
            <div class="<%= key %>"><%= string %></div>
        <% end %>
    <% end %>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav>
  <div>
    <div class="logo">
      <a href="<%= root_url %>">
        <div class="logo-img">
          <i class="fas fa-bread-slice"></i>
        </div>
        <span>Breddit</span>
      </a>
    </div>
    <%= link_to "Subs", subs_url, class: "subs" %>
  </div>
  <%= render "searches/form" %>
  <div>
    <% if current_user %>
      <a href="<%= user_url(current_user) %>", class="user-icon"><i class="fas fa-user"></i></a>
      <%= button_to "Log Out", session_url(current_user), method: :delete, class: "log-in" %>
    <% else %>
      <%= link_to "Log In", new_session_url, class: "log-in" %>
      <%= link_to "Sign Up", new_user_url, class: "sign-up" %>
    <% end %>
  </div>
  <!-- Mobile menu and search icon -->
  <div class="mobile-right">
    <button id="expand-search"><i class="fas fa-search"></i></button>
    <button id="expand-menu"><i class="fas fa-hamburger"></i></button>
    <ul id="mobile-menu" class="hide">
        <% if current_user %>
          <li><a href="<%= user_url(current_user) %>"><i class="fas fa-user"></i> <%= current_user.username %></a></li>
          <li><%= button_to "Log Out", session_url(current_user), method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_session_url %></li>
          <li><%= link_to "Sign Up", new_user_url %></li>
        <% end %>
        
        <li><%= link_to "Subs", subs_url %></li>
    </ul>
  </div>
</nav>