config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :destroy], param: :username do
    get 'activate', on: :collection
  end
  get '/users', to: 'users#new'
  
  resource :session, only: [:new, :create, :destroy]
  get '/session', to: 'sessions#new'

  resources :subs, except: [:destroy], param: :title do
    member { post :subscribe }
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member { post :upvote }
    member { post :downvote }
  end
  get '/posts', to: 'subs#index'

  resources :comments, only: [:create, :show, :destroy] do
    member { post :upvote }
    member { post :downvote }
  end

  resources :pages, only: [:index]

  resources :searches, only: [:index]
  get '/search', to: 'searches#index'

  root 'pages#index'
end

app/models/sub.rb
# title           string      required    unique
# description     text        required
# moderator       integer     required

class Sub < ApplicationRecord
  include Ordering
  EXCERPT_LENGTH = 247

  validates :title, :description, :moderator, presence: true
  validates :title, uniqueness: true, length: { minimum: MIN_TITLE, maximum: MAX_TITLE }, format: { with: URL_SAFE_REGEX, 
    message: 'allows only letters, numbers, and symbols -_$.+!*()' }
  
  belongs_to :user,
    class_name: 'User',
    primary_key: :id,
    foreign_key: :moderator

  has_many :post_subs

  has_many :posts,
    through: :post_subs

  has_many :subscriptions

  has_many :subscribers,
    through: :subscriptions,
    source: :user

  def to_param
    self.title
  end

  def add_moderator(user_id)
    self.moderator = user_id
  end

  def excerpt
    self.description.length <= EXCERPT_LENGTH ? self.description : self.description[0..EXCERPT_LENGTH] + '...'
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :not_logged_in, only: [:new, :create, :subscribe]
  before_action :wrong_user, only: [:edit, :update]

  def index
    @subs = Sub.alpha_order(:title)
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_new_params)
    @sub.add_moderator(current_user.id)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:error] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    sub_data = Sub.where(title: params[:title]).includes(posts: [:author, :votes, :subs]).create_order
    @sub = sub_data.first
    @moderator = @sub.user
    @posts = @sub.posts
    render :show
  end

  def edit
    @sub = Sub.find_by_title(params[:title])
    render :edit
  end

  def update
    @sub = Sub.find_by_title(params[:title])

    if @sub.update_attributes(sub_edit_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:error] = @sub.errors.full_messages
      render :edit
    end
  end

  def subscribe
    sub = Sub.find_by_title(params[:title])
    subscription = Subscription.new(user_id: current_user.id, sub_id: sub.id)
    if subscription.save
      flash[:notice] = 'You have subscribed successfully to this sub'
    else
      flash[:error] = subscription.errors.full_messages
    end
    redirect_to request.referrer
  end

  private

  def wrong_user
    sub = Sub.find_by_title(params[:title])
    return if sub.user == current_user
    redirect_to sub_url(sub)
  end

  def sub_new_params
    params.require(:sub).permit(:title, :description)
  end

  def sub_edit_params
    params.require(:sub).permit(:description)
  end
end

app/views/subs/_form.html.erb
<%= form_with model: sub, local: true do |form| %>
    <input type="hidden" id="sub_id" name="sub[id]" value="<%= sub.id %>">
    <div>
        <%= label :sub, :title %>
        <%= form.text_field :title, minlength: MIN_TITLE, maxlength: MAX_TITLE, required: true,
            placeholder: "Title", disabled: sub.persisted? %>
    </div>

    <div>
        <%= label :sub, :description %>
        <%= form.text_area :description, required: true, placeholder: "Description" %>
    </div>

    <div>
        <%= form.submit "Save" %>
    </div>
<% end %>

app/views/subs/_list_all.html.erb
<% subs.each do |sub| %>
    <% member_count = sub.subscriptions.count %>
    <div>
        <span class="sub-heading">
            <%= link_to "subs/#{sub.title}", sub_url(sub) %> 
            <span class="data">
                <%= member_count %> member<%= member_count == 1 ? "" : "s" %>
                <%= button_to('Join', subscribe_sub_url(sub), class: "button small") if current_user %>
            </span>
        </span>
        
        <p><%= sub.excerpt %></p>
    </div>
<% end %>

app/views/subs/edit.html.erb
<% @title = "Edit Sub" %>

<div class="form sub bottom-padding">
    <div class="logo-img">
      <i class="fas fa-bread-slice"></i>
    </div>

    <h1>Edit Sub</h1>

    <%= render "form", sub: @sub %>
</div>

app/views/subs/index.html.erb
<% @title = "All Subs" %>

<div class="sub bottom-padding">
    <div class="heading">
        <h1>All Subs</h1>
        <% if current_user %>
            <%= link_to "Create SubBreddit", new_sub_url, class: "button" %>
        <% end %>
    </div>

    <% if @subs.empty? %>
        <p class="nothing-posted">No subs yet</p>
    <% else %>
        <div class="list">
            <%= render "list_all", subs: @subs %>
        </div>
    <% end %>
</div>

app/views/subs/new.html.erb
<% @title = "New Sub" %>

<div class="form sub bottom-padding">
    <div class="logo-img">
      <i class="fas fa-bread-slice"></i>
    </div>
    
    <h1>New Sub</h1>

    <%= render "form", sub: @sub %>
</div>

app/views/subs/show.html.erb
<% @title = "Sub: #{@sub.title}" %>

<div class="sub bottom-padding">
<section class="details">
    <div class="heading">
        <h1>subs/<%= @sub.title %></h1>
        <%= button_to('Join', subscribe_sub_url(@sub), class: "button") if current_user %>
    </div>

    <p><%= @sub.description %></p>

    <div class="data">
        <span>
            Moderated by 
            <% if @moderator.username == DESTROYED %>
                <%= DESTROYED %>
            <% else %>
                <%= link_to @moderator.username, user_url(@moderator) %>
            <% end %>
        </span>

        <span><%= @sub.subscriptions.count %> members</span>
        <% if current_user == @moderator %>
            <span><%= link_to "Edit Sub", edit_sub_url(@sub) %></span>
        <% end %>
    </div>
</section>

<section class="post">
    <%= link_to "Create Post", new_post_url(sub_id: @sub.id), class: "button" %>
    <% if @posts.empty? %>
        <p class="nothing-posted">No posts to see here</p>
    <% else %>
        <%= render "posts/list", posts: @posts, short: true %>
     <% end %>
</section>
</div>