config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :destroy], param: :username do
    get 'activate', on: :collection
  end
  get '/users', to: 'users#new'
  
  resource :session, only: [:new, :create, :destroy]
  get '/session', to: 'sessions#new'

  resources :subs, except: [:destroy], param: :title do
    member { post :subscribe }
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member { post :upvote }
    member { post :downvote }
  end
  get '/posts', to: 'subs#index'

  resources :comments, only: [:create, :show, :destroy] do
    member { post :upvote }
    member { post :downvote }
  end

  resources :pages, only: [:index]

  resources :searches, only: [:index]
  get '/search', to: 'searches#index'

  root 'pages#index'
end

app/models/post.rb
# title       string        required
# url         text
# content     text
# sub_id      integer       required
# author_id   integer       required

class Post < ApplicationRecord
  include Ordering
  include Calcs
  include Voteable

  EXCERPT_LENGTH = 197
  LONG_EXCERPT_LENGTH = 997

  validates :title, :slug, presence: true
  validates :title, length: { minimum: MIN_POST, maximum: MAX_POST }
  before_validation :add_slug, :check_sub
  before_create :final_slug

  belongs_to :author,
    class_name: 'User',
    primary_key: :id,
    foreign_key: :author_id

  has_many :post_subs, 
    inverse_of: :post,
    dependent: :destroy

  has_many :subs,
    through: :post_subs

  has_many :comments,
    dependent: :destroy

  has_many :moderators,
    -> { distinct },
    through: :subs,
    source: :user

  def top_level_comments
    self.comments.where(parent_column_id: nil)
  end

  def check_sub
    errors.add(:post, 'must belong to 1-3 subs') unless self.subs.length.between?(1, 3)
  end

  def to_param
    "#{self.id}-#{self.slug}"
  end

  def final_slug
    self.slug = self.title.parameterize
  end

  def add_slug
    self.slug ||= self.title.parameterize
  end

  def excerpt
    return self.content if self.content.nil? || self.content.length <= EXCERPT_LENGTH
    self.content[0..EXCERPT_LENGTH] + '...'
  end

  def long_excerpt
    return self.content if self.content.nil? || self.content.length <= LONG_EXCERPT_LENGTH
    self.content[0..LONG_EXCERPT_LENGTH] + '...'
  end

  def add_author(author_id)
    self.author_id = author_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :not_logged_in, only: [:new, :create, :upvote, :downvote]
  before_action :wrong_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    @post_subs = []
    @subs = Sub.alpha_order(:title).select(:id, :title)
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.add_author(current_user.id)

    if @post.save
      redirect_to post_url(@post)
    else
      @post_subs = params[:post][:sub_ids][1..-1].map(&:to_i)
      @subs = Sub.alpha_order(:title).select(:id, :title)
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def show
    post_data = Post.where(id: params[:id]).includes(comments: [:author, :votes]).create_order
    @post = post_data.first
    @moderators = @post.moderators.pluck(:id)
    @comments = @post.comments
    @author = @post.author
    @subs = @post.subs.alpha_order(:title).select(:id, :title)
    render :show
  end

  def edit
    @post = Post.find_by_id(params[:id])
    @post_subs = @post.subs.pluck(:id)
    @subs = Sub.alpha_order(:title).select(:id, :title)
    render :edit
  end

  def update
    @post = Post.find_by_id(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      @post_subs = @post.subs.pluck(:id)
      @subs = Sub.alpha_order(:title).select(:id, :title)
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])

    if @post.destroy
      redirect_to root_url
    else
      flash[:error] = "Oops, something went wrong. Post still exists."
      render :show
    end
  end

  def upvote
    vote = Vote.new(user_id: current_user.id, voteable_type: 'Post', voteable_id: params[:id].to_i)
    flash[:error] = vote.errors.full_messages unless vote.upvote!
    redirect_to "#{request.referrer}#p-#{params[:id].to_i}"
  end

  def downvote
    vote = Vote.new(user_id: current_user.id, voteable_type: 'Post', voteable_id: params[:id].to_i)
    flash[:error] = vote.errors.full_messages unless vote.downvote!
    redirect_to "#{request.referrer}#p-#{params[:id].to_i}"
  end

  private

  def wrong_user
    post = Post.find_by_id(params[:id])
    return if post.author == current_user || post.moderators.include?(current_user)
    redirect_to post_url(post)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def upvote_percentage(post)
    total_votes = post.votes.length
    return 0 if total_votes.zero?

    score = post.vote_total * 1.0
    positive = score > 0 ? ( ( (total_votes - score) / 2 ) + score ) : ( (total_votes + score) / 2 )
    positive / total_votes * 100
  end
end

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |form| %>
    <div>
        <%= label :post, :title %>
        <%= form.text_field :title, minlength: MIN_POST, maxlength: MAX_POST, required: true, placeholder: "Title" %>
    </div>

    <div>
        <%= label :post, :url %>
        <%= form.text_field :url, placeholder: "Url" %>
    </div>

    <div>
        <%= label :post, :content %>
        <%= form.text_area :content, placeholder: "Content" %>
    </div>

    <div>
        <div>
            <div id="no-match" class="no-match invisible">Sub does not exist</div>
            <div class="sub-options">
                <label for="sub-choices">Select 1-3 subs to post in:</label>
                <input list="sub-options" id="sub-choices" type="text" placeholder="Find sub">
                <button id="add-sub">+</button>
            </div>
            <datalist id="sub-options">
                <% subs.each do |sub| %>
                    <option data-subid="sub_<%= sub.id %>" value="<%= sub.title %>">
                <% end %>
            </datalist>
        </div>

        <div class="selected-subs">
            <label>Selected Subs:</label>
            <input type="hidden" name="post[sub_ids][]" value="">
            <% subs.each do |sub| %>
                <% checked = params[:sub_id].to_i == sub.id || post_subs.include?(sub.id) %>
                <div class=<%= "hide" unless checked %>>
                    <input type="checkbox" id="sub_<%=sub.id%>" name="post[sub_ids][]" value="<%= sub.id %>"
                        <%= "checked" if checked %> >
                    <label for="sub_<%=sub.id%>"><%= sub.title %></label>
                </div>
            <% end %>
        </div>
    </div>

    <div>
        <%= form.submit "Save" %>
    </div>
<% end %>

<%= javascript_include_tag 'components/post_form' %>

app/views/posts/_fragment.html.erb
<%= button_to '+', upvote_post_url(post) %>
<%= post.vote_total %>
<%= button_to '-', downvote_post_url(post) %>

<h2><%= link_to post.title, post_url(post) %></h2>
<%= choose_url_format(post) %>
<p><%= post.long_excerpt %></p>
<p><%= post.comments.size %> comments</p>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
    <div id="p-<%= post.id %>" class="container">
        <div class="vote-btns">
            <span class="upvote"><%= button_to '⬆', upvote_post_url(post) %></span>
            <span class="vote-number"><%= post.vote_total %></span>
            <span class="downvote"><%= button_to '⬇', downvote_post_url(post) %></span>
        </div>

        <div class="data">
            Posted by <%= post.author.username == DESTROYED ? DESTROYED : link_to(post.author.username, user_url(post.author)) %> in: 
            <% post.subs.each do |sub| %>
                <%= link_to sub.title, sub_url(sub) %>
            <% end %>
        <%= post.time_ago %> ago
        </div>
        
        <h2><%= link_to post.title, post_url(post) %></h2>
        
        <div class="url-render">
            <%= choose_url_format(post) %>
        </div>

        <p><%= short ? post.excerpt : post.long_excerpt %></p>

        <div class="data">
            <i class="fas fa-comment-alt"></i> 
            <span class="heavy"><%= post.comments.size %> comments</span>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<% @title = "Edit Post" %>

<div class="form post bottom-padding">
    <div class="logo-img">
      <i class="fas fa-bread-slice"></i>
    </div>

    <h1>Edit a Post</h1>

    <%= render "form", post: @post, subs: @subs, post_subs: @post_subs %>
</div>

app/views/posts/new.html.erb
<% @title = "New Post" %>

<div class="form post bottom-padding">
    <div class="logo-img">
      <i class="fas fa-bread-slice"></i>
    </div>

    <h1>New Post</h1>

    <%= render "form", post: @post, subs: @subs, post_subs: @post_subs %>
</div>

app/views/posts/show.html.erb
<% @title = @post.title %>
<% @logged_in = !!current_user %>

<div class="post-details bottom-padding">
<section id="p-<%=@post.id%>" class="container post">
    <div class="vote-btns">
        <span class="upvote"><%= button_to '⬆', upvote_post_url(@post) %></span>
        <span class="vote-number"><%= @post.vote_total %></span>
        <span class="downvote"><%= button_to '⬇', downvote_post_url(@post) %></span>
    </div>

    <div class="data">
        Posted by: <%= @author.username == DESTROYED ? DESTROYED : link_to(@author.username, user_url(@author)) %> in: 
            <% @subs.each do |sub| %>
                <%= link_to sub.title, sub_url(sub) %>
            <% end %>
        <%= @post.time_ago %> ago
    </div>

    <h1><%= @post.title %></h1>

    <div class="url-render">
        <%= choose_url_format(@post) %>
    </div>

    <p><%= @post.content %></p>

    <div class="data">
        <i class="fas fa-comment-alt"></i> 
        <span class="heavy"><%= @post.comments.size %> Comments</span>
        <% if @logged_in && (current_user == @author || @moderators.include?(current_user.id)) %>
            <span class="heavy"><%= link_to "Edit Post", edit_post_url(@post) %></span>
            <span class="heavy delete-link"><%= button_to "Delete Post", post_url(@post), method: :delete %></span>
        <% end %>
        <div class="upvote-percentage"><%= upvote_percentage(@post).to_i %>% Upvoted</div>
    </div>

    <div class="thoughts">
        <h2>What are your thoughts?</h2>
        <% if @logged_in %>
            <%= render "comments/form", post_id: @post.id, parent_comment_id: nil %>
        <% else %>
            <p>Want to join in? Why not <%= link_to "sign up", new_user_url %>!</p>
        <% end %>
    </div>
</section>

<section class="comments">
    <%= formatted_comments(@comments, nil, 'flat') %>
</section>
</div>

<%= javascript_include_tag 'components/nested_comments' %>